//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDepartmentGroup
    {
        public DimDepartmentGroup()
        {
            this.DimDepartmentGroup1 = new HashSet<DimDepartmentGroup>();
            this.FactFinance = new HashSet<FactFinance>();
        }
    
        public int DepartmentGroupKey { get; set; }
        public Nullable<int> ParentDepartmentGroupKey { get; set; }
        public string DepartmentGroupName { get; set; }
    
        public virtual ICollection<DimDepartmentGroup> DimDepartmentGroup1 { get; set; }
        public virtual DimDepartmentGroup DimDepartmentGroup2 { get; set; }
        public virtual ICollection<FactFinance> FactFinance { get; set; }
    }
}
