//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public DimDate()
        {
            this.FactCallCenter = new HashSet<FactCallCenter>();
            this.FactCurrencyRate = new HashSet<FactCurrencyRate>();
            this.FactFinance = new HashSet<FactFinance>();
            this.FactInternetSales = new HashSet<FactInternetSales>();
            this.FactInternetSales1 = new HashSet<FactInternetSales>();
            this.FactInternetSales2 = new HashSet<FactInternetSales>();
            this.FactProductInventory = new HashSet<FactProductInventory>();
            this.FactResellerSales = new HashSet<FactResellerSales>();
            this.FactResellerSales1 = new HashSet<FactResellerSales>();
            this.FactResellerSales2 = new HashSet<FactResellerSales>();
            this.FactSalesQuota = new HashSet<FactSalesQuota>();
            this.FactSurveyResponse = new HashSet<FactSurveyResponse>();
        }
    
        public int DateKey { get; set; }
        public System.DateTime FullDateAlternateKey { get; set; }
        public byte DayNumberOfWeek { get; set; }
        public string EnglishDayNameOfWeek { get; set; }
        public string SpanishDayNameOfWeek { get; set; }
        public string FrenchDayNameOfWeek { get; set; }
        public byte DayNumberOfMonth { get; set; }
        public short DayNumberOfYear { get; set; }
        public byte WeekNumberOfYear { get; set; }
        public string EnglishMonthName { get; set; }
        public string SpanishMonthName { get; set; }
        public string FrenchMonthName { get; set; }
        public byte MonthNumberOfYear { get; set; }
        public byte CalendarQuarter { get; set; }
        public short CalendarYear { get; set; }
        public byte CalendarSemester { get; set; }
        public byte FiscalQuarter { get; set; }
        public short FiscalYear { get; set; }
        public byte FiscalSemester { get; set; }
    
        public virtual ICollection<FactCallCenter> FactCallCenter { get; set; }
        public virtual ICollection<FactCurrencyRate> FactCurrencyRate { get; set; }
        public virtual ICollection<FactFinance> FactFinance { get; set; }
        public virtual ICollection<FactInternetSales> FactInternetSales { get; set; }
        public virtual ICollection<FactInternetSales> FactInternetSales1 { get; set; }
        public virtual ICollection<FactInternetSales> FactInternetSales2 { get; set; }
        public virtual ICollection<FactProductInventory> FactProductInventory { get; set; }
        public virtual ICollection<FactResellerSales> FactResellerSales { get; set; }
        public virtual ICollection<FactResellerSales> FactResellerSales1 { get; set; }
        public virtual ICollection<FactResellerSales> FactResellerSales2 { get; set; }
        public virtual ICollection<FactSalesQuota> FactSalesQuota { get; set; }
        public virtual ICollection<FactSurveyResponse> FactSurveyResponse { get; set; }
    }
}
