//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProductSubcategory
    {
        public DimProductSubcategory()
        {
            this.DimProduct = new HashSet<DimProduct>();
        }
    
        public int ProductSubcategoryKey { get; set; }
        public Nullable<int> ProductSubcategoryAlternateKey { get; set; }
        public string EnglishProductSubcategoryName { get; set; }
        public string SpanishProductSubcategoryName { get; set; }
        public string FrenchProductSubcategoryName { get; set; }
        public Nullable<int> ProductCategoryKey { get; set; }
    
        public virtual ICollection<DimProduct> DimProduct { get; set; }
        public virtual DimProductCategory DimProductCategory { get; set; }
    }
}
