//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimSalesTerritory
    {
        public DimSalesTerritory()
        {
            this.DimEmployee = new HashSet<DimEmployee>();
            this.DimGeography = new HashSet<DimGeography>();
            this.FactInternetSales = new HashSet<FactInternetSales>();
            this.FactResellerSales = new HashSet<FactResellerSales>();
        }
    
        public int SalesTerritoryKey { get; set; }
        public Nullable<int> SalesTerritoryAlternateKey { get; set; }
        public string SalesTerritoryRegion { get; set; }
        public string SalesTerritoryCountry { get; set; }
        public string SalesTerritoryGroup { get; set; }
        public byte[] SalesTerritoryImage { get; set; }
    
        public virtual ICollection<DimEmployee> DimEmployee { get; set; }
        public virtual ICollection<DimGeography> DimGeography { get; set; }
        public virtual ICollection<FactInternetSales> FactInternetSales { get; set; }
        public virtual ICollection<FactResellerSales> FactResellerSales { get; set; }
    }
}
